### ISSUE TITLE
Release v0.1.0

### ISSUE THREAD

**Issue by mgrachev** [datanymizer/datanymizer#6]
What needs to be done for the v0.1.0 release.

Infrastructure:
- [x] Set up CI (check, fmt, build, clippy, test, audit) (#7);
- [x] Automate release process (linux, darwin, docker) (#13);
- [x] Create Homebrew formula;

Improvements:
- [x] Make uniqueness be available for other transformers (#8);
- [x] Add tables exclusion and inclusion at the schema creation level (#19);
